{
  "format_version": 1,
  "sksl": {
    "entrypoint": "spoiler_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float uTime;\nuniform vec2 uSize;\nuniform vec4 uColor;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nfloat FLT_flutter_local_hash21(inout vec2 p)\n{\n    p = fract(p * vec2(123.339996337890625, 345.45001220703125));\n    p += vec2(dot(p, p + vec2(34.345001220703125)));\n    return fract(p.x * p.y);\n}\n\nvoid FLT_main()\n{\n    vec2 fc = FLT_flutter_local_FlutterFragCoord();\n    float cell = 2.0;\n    vec2 gp = fc / vec2(cell);\n    vec2 id = floor(gp);\n    vec2 f = fract(gp) - vec2(0.5);\n    vec2 param = id;\n    float _73 = FLT_flutter_local_hash21(param);\n    float rnd = _73;\n    float tw = 0.5 + (0.5 * sin((uTime * (1.39999997615814208984375 + (rnd * 2.599999904632568359375))) + (rnd * 40.0)));\n    float present = step(0.300000011920928955078125, rnd);\n    float d2 = dot(f, f);\n    float dotMask = smoothstep(0.25, 0.01439999975264072418212890625, d2);\n    float dots = (dotMask * present) * (0.1500000059604644775390625 + (0.85000002384185791015625 * tw));\n    float base = 0.12999999523162841796875;\n    float edge = min(min(fc.x, uSize.x - fc.x), min(fc.y, uSize.y - fc.y));\n    float jitter = (fract(rnd * 43.0) - 0.5) * 7.0;\n    float feather = smoothstep(0.0, 3.0, edge + jitter);\n    float alpha = (clamp(base + (dots * 0.699999988079071044921875), 0.0, 1.0) * feather) * uColor.w;\n    fragColor = vec4(uColor.xyz * alpha, alpha);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uColor",
        "rows": 4,
        "type": 10
      }
    ]
  }
}